server:
  port: 8088

  ############################################################
  #
  # 配置数据源信息
  #
  ############################################################
spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    password: 123456
#  redis:
#    database: 1
#    host: 192.168.22.214
#    port: 6379
#    password: 752498
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl